/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager */

#ifndef _Included_com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager
#define _Included_com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager
 * Method:    disableIme
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager_disableIme
  (JNIEnv *, jobject);

/*
 * Class:     com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager
 * Method:    enableIme
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ddwhm_jesen_imblocker_immanager_linux_LinuxImManager_enableIme
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
